name: Experiments
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python
  - pandas
  - pip
  - plotly
  - numpy
  - scikit-learn
  - pathlib
  - tqdm
  - nbformat
  - ipywidgets
  - ipykernel
  - matplotlib
  - openai
  - python-dotenv
  - contextlib2
  # - pytorch 
  # - torchvision
  # - torchaudio
  # - pytorch-cuda=11.8
  # - cpuonly
  - pip:
    - datetime
    - pyyaml
    - streamlit
    - chromadb
    - bs4
    - langchain
    - langchain-community
    - langchain-openai
    - langchainhub
    - langsmith
    - tiktoken
    - lxml
    - chardet
    - gpt4all
    # - vllm
    - pypdf
    # - ray
    # - ochat