name: Experiments
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - pip
  - plotly
  - numpy
  - scikit-learn
  - pathlib
  - tqdm
  - nbformat
  - ipywidgets
  - ipykernel
  - matplotlib
  - openai
  - python-dotenv
  - contextlib2
  - pip:
    - datetime
    - pyyaml
    - streamlit
    - chromadb
    - bs4
    - langchain
    - langchain-community
    - langchainhub
    - langsmith
    - tiktoken
    - lxml
    - gpt4all
    - pypdf