name: Experiments
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - pip
  - plotly
  - numpy
  - scikit-learn
  - pathlib
  - tqdm
  - nbformat
  - ipywidgets
  - ipykernel
  - matplotlib
  - openai
  - langchain
  - python-dotenv
  - contextlib2
  - pip:
    - datetime
    - pyyaml