name: CryptoBotGpu
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.11
  - pandas
  - pandas-profiling
  - pip
  - plotly
  - numpy
  - pathlib
  - tqdm
  - ipywidgets
  - ipykernel
  - matplotlib
  - mlflow
  - ta-lib
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - xgboost
  - catboost
  - pip:
    - yfinance
    - datetime
    - sklearn
    - pyyaml
    - tensorflow-gpu==2.10